eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8003
spring:
  application:
    name: spring-cloud-consumer

feign:
  netty:
    enabled: true
management:
  security:
    enabled: false