eureka:
  client:
    service-url:
#      defaultZone: http://192.168.12.168:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8005
spring:
  application:
    name: spring-cloud-provider
  zipkin:
    enabled: true
    base-url: http://192.168.31.51:9411
  sleuth:
    sampler:
      percentage: 1.0
feign:
  netty:
    port: 20800
ribbon:
  eager-load:
    enabled: true

